---
- name: Install Checkmk Agent
  hosts: all
  become: yes
  tasks:
    - name: Ensure dependencies are installed
      apt:
        name:
          - wget
          - gnupg
        state: present
        update_cache: yes

    - name: Download Checkmk Agent package
      command: wget https://download.checkmk.com/checkmk/2.1.0/check-mk-agent_2.1.0p1-1_all.deb -O /tmp/check-mk-agent_2.1.0p1-1_all.deb
      args:
        creates: /tmp/check-mk-agent_2.1.0p1-1_all.deb

    - name: Install Checkmk Agent package
      apt:
        deb: /tmp/check-mk-agent_2.1.0p1-1_all.deb
        state: present

    - name: Ensure xinetd is installed
      apt:
        name: xinetd
        state: present

    - name: Configure xinetd for Checkmk Agent
      copy:
        dest: /etc/xinetd.d/check_mk
        content: |
          service check_mk
          {
            type           = UNLISTED
            port           = 6556
            socket_type    = stream
            protocol       = tcp
            wait           = no
            user           = root
            server         = /usr/bin/check_mk_agent
            log_on_success += USERID
            disable        = no
          }

    - name: Restart xinetd to apply Checkmk configuration
      service:
        name: xinetd
        state: restarted

    - name: Ensure xinetd is enabled and starts on boot
      systemd:
        name: xinetd
        enabled: yes
        state: started
